// waypoints.js — Virtual Zoo habitat configurations
// 10 stages, each with camera position, colors, stats, and panel content

export const NUM_STAGES = 10;

// Each waypoint defines a stage in the virtual zoo journey.
// cameraPos / cameraTarget are in world-space (THREE.Vector3-compatible plain objects).
// skyTopColor / skyHorizonColor / fogColor are [R,G,B] 0-255 arrays.
export const WAYPOINTS = [
  {
    index: 0,
    id: 'gateway',
    stage: 'STAGE I',
    zone: 'ENTRY PLAZA',
    hudZone: 'GATEWAY',
    name: 'The',
    nameItalic: 'Gateway',
    subtitle: 'Your wild journey begins here',
    cameraPos:    { x:  -65,  y:  28, z:   90 },
    cameraTarget: { x:    0,  y:   8, z:  -10 },
    fov: 48,
    skyTopColor:     [ 18,  36,  72 ],
    skyHorizonColor: [120, 160, 200 ],
    fogColor:        [210, 220, 230 ],
    fogNear: 500, fogFar: 2200,
    ambientColor: [255, 245, 220], ambientIntensity: 1.3,
    sunColor: [255, 240, 200], sunIntensity: 3.0,
    sunPos: { x: 150, y: 280, z: 80 },
    bloomStrength: 0.25,
    species: 0, temperature: 24, dangerLevel: 'NONE', timeOfDay: 'MORNING',
    stat1: { label: '📍 ZOO AREA', value: '2.4', unit: 'km²', sub: 'TOTAL SIZE' },
    stat2: { label: '🦁 TOTAL SPECIES', value: '340', unit: '', sub: 'ACROSS 9 ZONES' },
    graphLabel: 'VISITOR EXPERIENCE RATING',
    graphData: [0.35, 0.55, 0.65, 0.75, 0.85, 0.95, 1.0],
    description: `Welcome to the most immersive virtual zoo on Earth. Step through the grand gateway and prepare to encounter the extraordinary. Spanning over 2.4 km², this zoo is home to more than <strong>340 species</strong> across 9 distinct habitats.\n\nYour journey will carry you from the sun-baked African savanna to the frozen arctic tundra — from the canopy rainforest to the abyssal ocean deep. Every step is a new world. Every creature is a miracle.`,
    heroImg: '/assets/gateway.jpg',
    tags: ['WELCOME', '340 SPECIES', '9 HABITATS', 'FREE ENTRY'],
    footerText: 'STAGE I · GATEWAY · START YOUR JOURNEY',
    particleType: null,
    labelMarkers: [
      { pos: { x:  60, y: 18, z:  45 }, text: 'MAIN ENTRANCE' },
      { pos: { x: -90, y: 16, z:  75 }, text: 'INFO CENTER' },
      { pos: { x:  30, y: 14, z: -60 }, text: 'MAP KIOSK' },
    ],
  },
  {
    index: 1,
    id: 'savanna',
    stage: 'STAGE II',
    zone: 'AFRICAN SAVANNA',
    hudZone: 'SAVANNA',
    name: 'Savanna',
    nameItalic: 'Kingdom',
    subtitle: 'Where the wild things roam',
    cameraPos:    { x: 335,  y:  34, z: -150 },
    cameraTarget: { x: 380,  y:  16, z: -210 },
    fov: 46,
    skyTopColor:     [ 24,  48,  98 ],
    skyHorizonColor: [225, 160,  78 ],
    fogColor:        [235, 205, 135 ],
    fogNear: 400, fogFar: 1900,
    ambientColor: [255, 220, 150], ambientIntensity: 1.4,
    sunColor: [255, 210, 120], sunIntensity: 3.8,
    sunPos: { x: 300, y: 200, z: -400 },
    bloomStrength: 0.2,
    species: 48, temperature: 38, dangerLevel: 'MEDIUM', timeOfDay: 'AFTERNOON',
    stat1: { label: '🦁 APEX PREDATORS', value: '6', unit: '', sub: 'LIONS & CHEETAHS' },
    stat2: { label: '🌡 PEAK TEMP', value: '38', unit: '°C', sub: 'MID-AFTERNOON' },
    graphLabel: 'HERD DENSITY PROFILE',
    graphData: [0.4, 0.72, 0.9, 1.0, 0.85, 0.7, 0.52],
    description: `Sprawling across 140 hectares of sun-baked earth, the <strong>Savanna Kingdom</strong> is home to some of the most iconic animals on the planet. Towering giraffes browse acacia treetops while lion prides survey their territory from rocky outcrops.\n\nWitness the raw drama of the wild: zebra migrations, elephant family herds, and the patient stalk of the cheetah — the fastest land animal at <strong>112 km/h</strong>.`,
    heroImg: '/assets/savanna.jpg',
    tags: ['48 SPECIES', '140 HECTARES', '6 APEX PREDATORS', 'OPEN PLAINS'],
    footerText: 'STAGE II · SAVANNA · 38°C · MEDIUM DANGER',
    particleType: 'dust',
    labelMarkers: [
      { pos: { x: 388, y: 24, z: -228 }, text: 'LION TERRITORY' },
      { pos: { x: 320, y: 28, z: -155 }, text: 'GIRAFFE HERD' },
      { pos: { x: 430, y: 18, z: -290 }, text: 'WATERING HOLE' },
    ],
  },
  {
    index: 2,
    id: 'rainforest',
    stage: 'STAGE III',
    zone: 'TROPICAL RAINFOREST',
    hudZone: 'RAINFOREST',
    name: 'The',
    nameItalic: 'Rainforest',
    subtitle: 'Life finds a way',
    cameraPos:    { x: 650,  y:  45, z:  -50 },
    cameraTarget: { x: 695,  y:  42, z:  -95 },
    fov: 46,
    skyTopColor:     [ 10,  32,  20 ],
    skyHorizonColor: [ 50, 112,  68 ],
    fogColor:        [ 78, 145,  98 ],
    fogNear: 280, fogFar: 1400,
    ambientColor: [150, 220, 150], ambientIntensity: 1.2,
    sunColor: [220, 255, 180], sunIntensity: 2.5,
    sunPos: { x: 600, y: 420, z: -200 },
    bloomStrength: 0.3,
    species: 127, temperature: 28, dangerLevel: 'HIGH', timeOfDay: 'MIDDAY',
    stat1: { label: '🐆 CANOPY LAYERS', value: '4', unit: '', sub: 'EMERGENT TO FLOOR' },
    stat2: { label: '🌿 HUMIDITY', value: '85', unit: '%', sub: 'YEAR-ROUND' },
    graphLabel: 'BIODIVERSITY INDEX',
    graphData: [0.5, 0.8, 1.0, 0.95, 0.9, 0.85, 1.0],
    description: `The most biodiverse habitat on Earth, our <strong>Tropical Rainforest</strong> holds more species per square metre than anywhere else in the zoo. The air is thick with humidity and exotic birdsong fills every canopy layer.\n\nGorilla families nest in the emergent layer while jaguars patrol the shadowed undergrowth. Poison dart frogs — brilliant with warning colours — signal deadly danger from the moss-covered floor.`,
    heroImg: '/assets/rainforest.jpg',
    tags: ['127 SPECIES', '85% HUMIDITY', 'CONSERVATION ZONE', '4 CANOPY LAYERS'],
    footerText: 'STAGE III · RAINFOREST · 28°C · HIGH DANGER',
    particleType: 'leaves',
    labelMarkers: [
      { pos: { x: 698, y: 58, z:  -98 }, text: 'GORILLA TERRITORY' },
      { pos: { x: 652, y: 44, z:  -52 }, text: 'CANOPY WALKWAY' },
      { pos: { x: 720, y: 38, z: -140 }, text: 'JAGUAR WATCH' },
    ],
  },
  {
    index: 3,
    id: 'arctic',
    stage: 'STAGE IV',
    zone: 'ARCTIC TUNDRA',
    hudZone: 'ARCTIC',
    name: 'Arctic',
    nameItalic: 'Tundra',
    subtitle: 'The frozen frontier',
    cameraPos:    { x: 910,  y:  58, z:  150 },
    cameraTarget: { x: 955,  y:  50, z:  205 },
    fov: 48,
    skyTopColor:     [ 28,  58, 118 ],
    skyHorizonColor: [140, 202, 242 ],
    fogColor:        [218, 238, 252 ],
    fogNear: 350, fogFar: 1800,
    ambientColor: [200, 225, 255], ambientIntensity: 1.3,
    sunColor: [240, 250, 255], sunIntensity: 2.2,
    sunPos: { x: 800, y: 160, z: -80 },
    bloomStrength: 0.35,
    species: 22, temperature: -18, dangerLevel: 'LOW', timeOfDay: 'DAWN',
    stat1: { label: '❄ ICE THICKNESS', value: '3.2', unit: 'm', sub: 'AVERAGE PACK ICE' },
    stat2: { label: '🐻‍❄️ POLAR BEARS', value: '4', unit: '', sub: 'IN THIS HABITAT' },
    graphLabel: 'TEMPERATURE PROFILE',
    graphData: [0.12, 0.18, 0.14, 0.1, 0.22, 0.18, 0.1],
    description: `Step into the silence of the <strong>Arctic Tundra</strong> — a world of ice, wind, and extraordinary adaptation. The temperature plunges to −18°C and the permafrost stretches endlessly in every direction.\n\nOur polar bears, undisputed lords of the ice, weigh over 600 kg and can smell prey from 32 km away. Arctic foxes in pristine white winter coats ghost across the frozen surface like living spirits.`,
    heroImg: '/assets/arctic.jpg',
    tags: ['22 SPECIES', '−18°C', 'PACK ICE 3.2M', 'ENDANGERED HABITAT'],
    footerText: 'STAGE IV · ARCTIC · −18°C · ICE HABITAT',
    particleType: 'snow',
    labelMarkers: [
      { pos: { x: 968, y: 68, z: 228 }, text: 'POLAR BEAR DEN' },
      { pos: { x: 908, y: 55, z: 162 }, text: 'ICE CAP · 3.2M' },
      { pos: { x: 948, y: 48, z: 188 }, text: 'ARCTIC FOX TRAIL' },
    ],
  },
  {
    index: 4,
    id: 'ocean',
    stage: 'STAGE V',
    zone: 'DEEP OCEAN',
    hudZone: 'OCEAN DEEP',
    name: 'Ocean',
    nameItalic: 'Deep',
    subtitle: 'The last frontier on Earth',
    cameraPos:    { x: 785,  y:  24, z:  510 },
    cameraTarget: { x: 825,  y:  10, z:  565 },
    fov: 48,
    skyTopColor:     [ 10,  28,  68 ],
    skyHorizonColor: [ 20,  80, 142 ],
    fogColor:        [ 35, 110, 182 ],
    fogNear: 250, fogFar: 1200,
    ambientColor: [100, 170, 240], ambientIntensity: 1.0,
    sunColor: [140, 210, 255], sunIntensity: 2.0,
    sunPos: { x: 700, y: 300, z: 300 },
    bloomStrength: 0.4,
    species: 89, temperature: 4, dangerLevel: 'HIGH', timeOfDay: 'DUSK',
    stat1: { label: '🦈 SHARK SPECIES', value: '12', unit: '', sub: 'INCL. GREAT WHITE' },
    stat2: { label: '🌊 TANK VOLUME', value: '40M', unit: 'L', sub: 'DEEPEST IN WORLD' },
    graphLabel: 'OCEAN DEPTH PROFILE',
    graphData: [1.0, 0.8, 0.62, 0.42, 0.3, 0.2, 0.1],
    description: `Plunge into the <strong>Ocean Deep</strong> — a vast aquatic world containing over 40 million litres of seawater. From sunlit shallows to abyssal dark, life thrives in every pressure layer of the ocean.\n\n12 shark species patrol these waters, including the legendary <strong>great white shark</strong>. Graceful manta rays spiral overhead while bioluminescent jellyfish pulse in the depths far below.`,
    heroImg: '/assets/ocean.jpg',
    tags: ['89 SPECIES', '40M LITRES', '40M DEEP', 'BIOLUMINESCENT'],
    footerText: 'STAGE V · OCEAN DEEP · 4°C · HIGH DANGER',
    particleType: 'bubbles',
    labelMarkers: [
      { pos: { x: 832, y: 14, z: 582 }, text: 'GREAT WHITE ZONE' },
      { pos: { x: 782, y: 12, z: 525 }, text: 'CORAL REEF' },
      { pos: { x: 855, y:  8, z: 555 }, text: 'ABYSSAL TRENCH' },
    ],
  },
  {
    index: 5,
    id: 'badlands',
    stage: 'STAGE VI',
    zone: 'DESERT BADLANDS',
    hudZone: 'BADLANDS',
    name: 'Reptile',
    nameItalic: 'Badlands',
    subtitle: 'Masters of survival',
    cameraPos:    { x: 545,  y:  32, z:  685 },
    cameraTarget: { x: 585,  y:  20, z:  735 },
    fov: 48,
    skyTopColor:     [ 45,  28,  14 ],
    skyHorizonColor: [225, 140,  68 ],
    fogColor:        [240, 185, 110 ],
    fogNear: 400, fogFar: 1800,
    ambientColor: [255, 215, 130], ambientIntensity: 1.6,
    sunColor: [255, 180, 70], sunIntensity: 4.2,
    sunPos: { x: 400, y: 150, z: 500 },
    bloomStrength: 0.15,
    species: 34, temperature: 52, dangerLevel: 'EXTREME', timeOfDay: 'NOON',
    stat1: { label: '🦎 REPTILE SPECIES', value: '34', unit: '', sub: 'MOST VENOMOUS EARTH' },
    stat2: { label: '🌡 GROUND TEMP', value: '52', unit: '°C', sub: 'PEAK SURFACE' },
    graphLabel: 'HEAT INTENSITY CURVE',
    graphData: [0.28, 0.52, 0.72, 1.0, 0.96, 0.82, 0.62],
    description: `In the shimmering heat of the <strong>Reptile Badlands</strong>, survival is an art form. The komodo dragon — largest living lizard at 3 metres — patrols cracked red earth with prehistoric authority.\n\nRattlesnakes, gila monsters, and the deadly inland taipan — most venomous snake in the world — lurk in shadows cast by desert boulders. Ground temperature can reach <strong>52°C</strong> at peak sun. Every step here is a gamble.`,
    heroImg: '/assets/badlands.jpg',
    tags: ['34 SPECIES', '52°C', 'EXTREME DANGER', 'PREHISTORIC ZONE'],
    footerText: 'STAGE VI · BADLANDS · 52°C · EXTREME HEAT',
    particleType: 'heat',
    labelMarkers: [
      { pos: { x: 590, y: 28, z: 742 }, text: 'KOMODO TERRITORY' },
      { pos: { x: 545, y: 24, z: 682 }, text: 'HEAT SHIMMER ZONE' },
      { pos: { x: 615, y: 22, z: 710 }, text: 'VENOM RESEARCH' },
    ],
  },
  {
    index: 6,
    id: 'aviary',
    stage: 'STAGE VII',
    zone: 'THE GRAND AVIARY',
    hudZone: 'AVIARY',
    name: 'The',
    nameItalic: 'Aviary',
    subtitle: 'A symphony of wings',
    cameraPos:    { x:  75,  y:  70, z:  745 },
    cameraTarget: { x: 105,  y:  65, z:  800 },
    fov: 48,
    skyTopColor:     [ 18,  42,  85 ],
    skyHorizonColor: [130, 202, 242 ],
    fogColor:        [150, 222, 202 ],
    fogNear: 350, fogFar: 1600,
    ambientColor: [220, 250, 255], ambientIntensity: 1.2,
    sunColor: [255, 250, 220], sunIntensity: 2.6,
    sunPos: { x: 0, y: 420, z: 600 },
    bloomStrength: 0.22,
    species: 185, temperature: 26, dangerLevel: 'NONE', timeOfDay: 'AFTERNOON',
    stat1: { label: '🦜 BIRD SPECIES', value: '185', unit: '', sub: '60 ENDANGERED' },
    stat2: { label: '🏛 DOME HEIGHT', value: '45', unit: 'm', sub: 'LARGEST IN WORLD' },
    graphLabel: 'FLIGHT ACTIVITY PATTERN',
    graphData: [0.58, 0.8, 1.0, 0.92, 0.72, 0.88, 0.96],
    description: `Soar beneath the vast glass dome of the <strong>Grand Aviary</strong> — 45 metres high and home to 185 bird species from every continent. From the iridescent flash of the kingfisher to the slow majesty of the Andean condor, every moment here is a spectacle.\n\nOver 60 of these species are endangered in the wild. Our aviary is a critical <strong>conservation breeding ground</strong>, helping populations recover one generation at a time.`,
    heroImg: '/assets/aviary.jpg',
    tags: ['185 SPECIES', '45M DOME', '60 ENDANGERED', 'BREEDING PROGRAM'],
    footerText: 'STAGE VII · AVIARY · 26°C · GLASS DOME',
    particleType: 'birds',
    labelMarkers: [
      { pos: { x: 115, y: 82, z: 825 }, text: 'CONDOR TERRITORY' },
      { pos: { x:  82, y: 65, z: 782 }, text: 'HUMMINGBIRD GARDEN' },
      { pos: { x: 125, y: 72, z: 798 }, text: 'NEST PLATFORMS' },
    ],
  },
  {
    index: 7,
    id: 'nightsafari',
    stage: 'STAGE VIII',
    zone: 'NIGHT SAFARI',
    hudZone: 'NIGHT SAFARI',
    name: 'Night',
    nameItalic: 'Safari',
    subtitle: 'Darkness reveals its secrets',
    cameraPos:    { x: -180,  y:  34, z:  610 },
    cameraTarget: { x: -150,  y:  24, z:  660 },
    fov: 48,
    skyTopColor:     [  8,  14,  32 ],
    skyHorizonColor: [ 35,  55,  98 ],
    fogColor:        [ 30,  45,  85 ],
    fogNear: 200, fogFar: 1000,
    ambientColor: [120, 150, 230], ambientIntensity: 0.8,
    sunColor: [180, 195, 255], sunIntensity: 1.0,
    sunPos: { x: -300, y: 100, z: 400 },
    bloomStrength: 0.65,
    species: 56, temperature: 18, dangerLevel: 'MEDIUM', timeOfDay: 'NIGHT',
    stat1: { label: '🌙 NOCTURNAL SPP.', value: '56', unit: '', sub: 'ACTIVE AFTER DARK' },
    stat2: { label: '👁 NIGHT VISION', value: '8×', unit: '', sub: 'VS HUMAN SIGHT' },
    graphLabel: 'NOCTURNAL ACTIVITY LEVEL',
    graphData: [0.0, 0.08, 0.28, 0.68, 1.0, 0.92, 0.82],
    description: `As the sun sets over the <strong>Night Safari</strong>, the world transforms. Animals that hide from the day's heat emerge: leopards, owls, bush babies, and the ghostly aye-aye with its enormous reflective eyes.\n\nOur specially designed red-light pathway lets your eyes adapt naturally. The owl's hearing is so precise it can locate a mouse beneath <strong>30 cm of snow</strong>. Here, darkness is not absence — it is full of life.`,
    heroImg: '/assets/nightsafari.jpg',
    tags: ['56 SPECIES', 'RED LIGHT PATH', 'NOCTURNAL ONLY', 'INFRARED TOUR'],
    footerText: 'STAGE VIII · NIGHT SAFARI · 18°C · AFTER DARK',
    particleType: 'fireflies',
    labelMarkers: [
      { pos: { x: -152, y: 28, z: 668 }, text: 'LEOPARD WATCH' },
      { pos: { x: -188, y: 22, z: 618 }, text: 'FIREFLY MEADOW' },
      { pos: { x: -168, y: 18, z: 648 }, text: 'OWL TERRITORY' },
    ],
  },
  {
    index: 8,
    id: 'nursery',
    stage: 'STAGE IX',
    zone: 'THE NURSERY',
    hudZone: 'NURSERY',
    name: 'The',
    nameItalic: 'Nursery',
    subtitle: 'Where hope is born',
    cameraPos:    { x: -260,  y:  28, z:  280 },
    cameraTarget: { x: -220,  y:  15, z:  330 },
    fov: 46,
    skyTopColor:     [ 18,  38,  82 ],
    skyHorizonColor: [198, 228, 252 ],
    fogColor:        [218, 235, 245 ],
    fogNear: 450, fogFar: 2000,
    ambientColor: [240, 250, 255], ambientIntensity: 1.3,
    sunColor: [255, 252, 230], sunIntensity: 2.8,
    sunPos: { x: -400, y: 320, z: 100 },
    bloomStrength: 0.28,
    species: 28, temperature: 22, dangerLevel: 'NONE', timeOfDay: 'GOLDEN HOUR',
    stat1: { label: '🐾 NEWBORNS 2025', value: '28', unit: '', sub: 'THIS YEAR' },
    stat2: { label: '💚 SURVIVAL RATE', value: '94', unit: '%', sub: 'ABOVE GLOBAL AVG' },
    graphLabel: 'CONSERVATION SUCCESS RATE',
    graphData: [0.38, 0.5, 0.58, 0.68, 0.8, 0.88, 0.94],
    description: `The <strong>Nursery</strong> is where conservation comes to life. Soft meadows and gentle pens shelter some of the world's rarest young animals — red panda cubs, snow leopard kittens, elephant calves, and baby pygmy hippos.\n\nWith a 94% survival rate, our nursery exceeds global conservation benchmarks. Every birth here represents a <strong>victory for the wild</strong> — a debt repaid, one generation at a time.`,
    heroImg: '/assets/nursery.jpg',
    tags: ['28 NEWBORNS', '94% SURVIVAL', 'CONSERVATION', 'RARE SPECIES'],
    footerText: 'STAGE IX · NURSERY · 22°C · BREEDING PROGRAM',
    particleType: 'sparkles',
    labelMarkers: [
      { pos: { x: -222, y: 18, z: 342 }, text: 'ELEPHANT CALVES' },
      { pos: { x: -262, y: 16, z: 298 }, text: 'SNOW LEOPARD CUBS' },
      { pos: { x: -242, y: 14, z: 318 }, text: 'RED PANDA PENS' },
    ],
  },
  {
    index: 9,
    id: 'archive',
    stage: 'STAGE X',
    zone: 'THE ARCHIVE',
    hudZone: 'THE ARCHIVE',
    name: 'The',
    nameItalic: 'Archive',
    subtitle: 'Every life leaves a mark',
    cameraPos:    { x: -140,  y:  42, z:  -40 },
    cameraTarget: { x:  -82,  y:  28, z:  -18 },
    fov: 46,
    skyTopColor:     [ 12,  18,  42 ],
    skyHorizonColor: [ 58,  82, 135 ],
    fogColor:        [ 98, 112, 142 ],
    fogNear: 600, fogFar: 2400,
    ambientColor: [220, 230, 255], ambientIntensity: 1.1,
    sunColor: [250, 230, 190], sunIntensity: 2.0,
    sunPos: { x: -100, y: 420, z: -200 },
    bloomStrength: 0.2,
    species: 340, temperature: 20, dangerLevel: 'NONE', timeOfDay: 'DUSK',
    stat1: { label: '📚 RECORDS KEPT', value: '12,400', unit: '', sub: 'ANIMAL HISTORIES' },
    stat2: { label: '🌍 CONSERVATION', value: '₹4.2Cr', unit: '', sub: 'DONATED THIS YEAR' },
    graphLabel: 'SPECIES ENCOUNTERED THIS JOURNEY',
    graphData: [0, 0.14, 0.51, 0.58, 0.84, 0.94, 1.0],
    description: `The <strong>Archive</strong> is the soul of this zoo — a living record of every animal, every birth, every loss, and every triumph. Over 12,400 individual animal histories are documented here, spanning five decades of conservation.\n\nThis journey through 9 habitats has brought you face to face with 340 species. Each one is a thread in the fabric of life on Earth. The archive asks only one question: <strong>what will you do to protect them?</strong>`,
    heroImg: '/assets/gateway.jpg',
    tags: ['340 SPECIES', '12,400 RECORDS', '50 YEARS', 'CONSERVATION LEGACY'],
    footerText: 'STAGE X · THE ARCHIVE · END OF JOURNEY',
    particleType: null,
    labelMarkers: [
      { pos: { x:  -82, y: 38, z:  -28 }, text: 'CONSERVATION HUB' },
      { pos: { x: -152, y: 35, z:  -62 }, text: 'SPECIES DATABASE' },
      { pos: { x: -112, y: 32, z:  -48 }, text: 'GALLERY OF LIFE' },
    ],
  },
];

// Zone centers derived from cameraTarget positions — used by terrain.js for zone coloring
export const ZONE_CENTERS = WAYPOINTS.map(wp => ({
  x: wp.cameraTarget.x,
  z: wp.cameraTarget.z,
  color: getZoneColor(wp.id),
  baseHeight: getZoneHeight(wp.id),
  noiseAmp: getZoneNoise(wp.id),
}));

function getZoneColor(id) {
  const map = {
    gateway:     [0.78, 0.74, 0.62],
    savanna:     [0.85, 0.72, 0.35],
    rainforest:  [0.28, 0.65, 0.22],
    arctic:      [0.92, 0.96, 1.00],
    ocean:       [0.15, 0.48, 0.75],
    badlands:    [0.82, 0.45, 0.22],
    aviary:      [0.42, 0.78, 0.42],
    nightsafari: [0.22, 0.28, 0.48],
    nursery:     [0.55, 0.82, 0.48],
    archive:     [0.62, 0.58, 0.52],
  };
  return map[id] || [0.6, 0.6, 0.6];
}

function getZoneHeight(id) {
  const map = {
    gateway: 5, savanna: 2, rainforest: 18, arctic: 32,
    ocean: -10, badlands: 3, aviary: 9, nightsafari: 5,
    nursery: 6, archive: 12,
  };
  return map[id] ?? 5;
}

function getZoneNoise(id) {
  const map = {
    gateway: 10, savanna: 8, rainforest: 28, arctic: 16,
    ocean: 4, badlands: 5, aviary: 10, nightsafari: 8,
    nursery: 10, archive: 9,
  };
  return map[id] ?? 10;
}
